### ISSUE TITLE
Issue with old pydantic

### ISSUE THREAD

**Issue by kmike** [scrapy-plugins/scrapy-spider-metadata#6]
```py
import enum
import pydantic
import scrapy

from scrapy_spider_metadata import get_spider_metadata, Args

class MyOptions(str, enum.Enum):
    foo = "foo"
    bar = "bar"

class MyArgs(pydantic.BaseModel):
    opt: MyOptions = MyOptions.foo
        
class MySpider(Args[MyArgs], scrapy.Spider):
    pass        
```

In this example `get_spider_metadata(MySpider, normalize=True)` raises TypeError. Python 3.8, pydantic 1.8.2.

**Comment by wRAR** [comment]
We test on pydantic 1.0.0 where this works. It breaks on the latest 1.x and on 1.8.2.

**Comment by kmike** [comment]
I think not supporting very old pydantic is fine, as soon as we support at least some 1.x version. But it seems the issue is not with very old pydantic, but with recent 1.x, right? In this case we can have 3 envs (if supporting very old pydantic is easy), or switch to 2 (dropping support for old pydantic, if it helps).

**Comment by wRAR** [comment]
The schema output is also different between different 1.6-1.10 versions (e.g. using or not using allOf/anyOf). I think it should be possible to write normalization support for all versions but I don't think testing all of them is practical (though technically easy, just make  test envs for all different versions), and testing the non-normalized schemas for many different versions is even worse as we currently check exact results and so we would need to save many long fixtures for all tested versions.

One option I see is supporting 1.9 and 1.10 (1.9.0 was released on Dec 31, 2021), making a test env for 1.9.0 and dropping all earlier versions. Not sure if the schema code is different in 1.9 and 1.10 but on out test case the output is the same for them.

Additionally, I wonder if different 2.x versions (including future ones) also have different output.

**Comment by kmike** [comment]
I think that's fine to support pydantic 1.9+.

**Comment by wRAR** [comment]
I've run the tests with all minor pydantic versions between 2.0 and 2.4 and they work. Still, we decided that if in the future some change makes the non-normalized schema check fail we want to just drop this check.
